### ISSUE TITLE
a button cannot be shrinked in a normal cell or smaller in gtksheet.

### ISSUE THREAD

**Issue by songqingshan** [fpaquet/gtksheet#11]
A gtkbutton cannot be shrinked in a normal cell or to smaller in gtksheet.
The column width seems can not be customised or controlled.

**Comment by fpaquet** [comment]
The column width can be changed programmatically by setting "width" property.

To circumvent cell content allocation policy, you can pack your button into a box with disabled "fill" property.

**Comment by fpaquet** [comment]
https://fpaquet.github.io/gtksheet/reference/GtkSheetColumn.html#GtkSheetColumn.properties

**Comment by songqingshan** [comment]
Hello Fredy,

I can not circumvent cell content allocation policy because I need the button and fill property simultaneously . In other words, I use the button to fill the cell.
Thanks,
Song


________________________________
