### ISSUE TITLE
Make GtkSheetColumn its own proper object?

### ISSUE THREAD

**Issue by Xliff** [fpaquet/gtksheet#14]
Right now, to use any of the GtkSheetColumn functions, you still need to supply the GtkSheet pointer and the column  number. Currently, the GtkSheetColumn struct has a GtkSheet member. Are there any thoughts of putting both GtkSheet _and_ the column value into the GtkSheetColumn struct and then using that for the column functions?

Would you be interested in a PR that does this conversion?

**Comment by fpaquet** [comment]
Somewhat late, but i didn't get notifications for the sheet issues.

The column number is only avaliable after column has been put into a sheet.
