### ISSUE TITLE
Activate signal is fired for hidden rows

### ISSUE THREAD

**Issue by camilstaps** [fpaquet/gtksheet#18]
In a sheet with hidden rows, if you move from one cell to another and thereby skip hidden cells, the activate signal is still fired for these cells.

For example, if row 1 and 3 are shown but 2 is hidden, and if you move from row 1 to 3 by pressing enter, an activate signal is sent for the cell in row 2. I believe this should not happen.

**Comment by fpaquet** [comment]
Added "Hide Column", "Hide Row" to popup menu of folder 2 of testgtksheet (Branch gtk3_fixes).
This issue cannot be reproduced with sheet V4.3.4.
