### ISSUE TITLE
GtkSheet accesses private variables

### ISSUE THREAD

**Issue by lfaraone** [fpaquet/gtksheet#2]
Despite building from the latest sources, GtkSheet still accesses private member variables of GTK+.

See http://bugs.debian.org/549758

> gtkitementry.c: In function 'gtk_entry_real_insert_text':
> gtkitementry.c:696: error: 'GtkEntry' has no member named 'n_bytes'

http://github.com/vhernandez/gtksheet/blob/master/gtksheet/gtkitementry.c#L735
if (new_text_length + entry->n_bytes + 1 > entry->text_size)

"n_bytes is a private part of GtkEntry and gtksheet never had any right
to expect to be able to access it."

**Comment by fpaquet** [comment]
The GtkSheet project is being restarted.
We are starting with a fresh clone of GtkExtra.
