### ISSUE TITLE
Glade support doesn't respect configure prefix

### ISSUE THREAD

**Issue by ivanbakel** [fpaquet/gtksheet#22]
The build system always tries to install Glade resources to the same directories, which are the ones obtained by a `pkg-config` query.

Instead I think it should respect the `$prefix` variable in the configure system, so that the Glade resources could be placed elsewhere for packaging.

**Comment by fpaquet** [comment]
How can you tell Glade, to search for catalogs in other paths as the ones precompiled into glade?

**Comment by fpaquet** [comment]
We're also using a non-standard prefix here.
You can put non-standard locations into XDG_ env vars, before starting glade:

```
/usr/bin/env XDG_DATA_HOME=$prefix/share XDG_DATA_DIRS=$prefix/share:/usr/share $prefix/bin/glade
```
