### ISSUE TITLE
GtkSheet misreports its own introspection version

### ISSUE THREAD

**Issue by ivanbakel** [fpaquet/gtksheet#23]
This came about trying to use `haskell-gi` to autogenerate bindings to GtkSheet using the introspection features.

GtkSheet seems to conflictingly report its own version as `4.3.2` in files and `4.0` in filenames. This apparently breaks the `gir` repository, which is unable to find the `.typelib` file for GtkSheet with the (reported) version 4.3.2, but is able to find the one with version 4.0, though it then complains that there's a version mismatch.

This can be tested with
```
g-ir-inspect GtkSheet --version=4.3.2 --print-typelibs
```
Which fails, not finding the `.typelib` file, and
```
g-ir-inspect GtkSheet --version=4.0 --print-typelibs
```
Which initially succeeds, but then errors as the `.typelib` contains the wrong version number.

**Comment by ivanbakel** [comment]
This can be solved by renaming the `.typelib` file to have the correct version in the name - `4.3.2`. This works as normal, even while the `gir` file has version `4.0` in the name.

**Comment by arunisaac** [comment]
I ran into the same issue when using guile-gi. I am working around it for now by renaming the typelib file as ivanbakel suggests.

**Comment by fpaquet** [comment]
Ist this related to issue #13 ?

**Comment by arunisaac** [comment]
I don't know what the gir file in #13 is for, but certainly the typelib
has the wrong version in its filename.

**Comment by fpaquet** [comment]
Thank you for reporting. 
I will check it out when making next release.

**Comment by fpaquet** [comment]
With meson build, typelib file is named GtkSheet-4.3.4.typelib and g-ir-inspect is working.
When using ./configure, output files have wrong names.

**Comment by fpaquet** [comment]
I found a way to fix hardcoded gir filenames in Makefile.am:
https://stackoverflow.com/questions/34205092/autotool-automake-output-executable-filename-with-version

**Comment by fpaquet** [comment]
pushed fix to branch gtk3_fixes

To git@github.com:fpaquet/gtksheet.git
   b148681..7c8078c  gtk3_fixes -> gtk3_fixes
