### ISSUE TITLE
Function prototype of gtk_sheet_column_button_add_label in the documentation

### ISSUE THREAD

**Issue by arunisaac** [fpaquet/gtksheet#24]
Hi,

The documentation at https://fpaquet.github.io/gtksheet/tutorial/x114.html#SEC-FUNCTIONSTHATSETROWCOLUMNS mentions `gint row` as the second argument to gtk_sheet_column_button_add_label. That should probably be `gint column`.

Thanks!

**Comment by fpaquet** [comment]
Fixed in gtk3_fixes branch.

Thank you for reporting.
