### ISSUE TITLE
the grid lines inside gtksheet are missing since 4.3.0.

### ISSUE THREAD

**Issue by songqingshan** [fpaquet/gtksheet#27]

**Comment by songqingshan** [comment]
since 4.3.0, gtksheet default does not show grid line. I suggest gtksheet default show grid line. and then use gtk_sheet_show_grid to set it without grid line if user needs. 
More import for the outlook, some lines are missing. Please take a look at the attached file.

**Comment by fpaquet** [comment]
Yes, this was done on purpose because it provides a more modern look.

Very clear to me, that this change doesn't maintain full backward compatibility.
Generally i'm very careful, keeping full backward compatibility.

You can simply re-enable the gridlines by calling gtk_sheet_show_grid().
