### ISSUE TITLE
GtkSpinButton column issue in testGtkSheet

### ISSUE THREAD

**Issue by songqingshan** [fpaquet/gtksheet#28]
Gtk-WARNING **: 00:48:37.253: for_size smaller than min-size (26 < 32) while measuring gadget (node entry, owner GtkSpinButton)

 Gtk-CRITICAL **: 00:48:37.254: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

**Comment by fpaquet** [comment]
the testgtksheet app has a working GtkSpinButton in example "Folder 3"
Just enter some data to see it.

Maybe just increase column width, to get it working.
