### ISSUE TITLE
gtk_sheet_put () issue in gtksheet

### ISSUE THREAD

**Issue by songqingshan** [fpaquet/gtksheet#29]
Gtk-WARNING **: 22:29:03.191: Can't set a parent on widget which has a parent

**Comment by fpaquet** [comment]
Do you have more details?

**Comment by songqingshan** [comment]
my stack trace only provides those information.
Thanks for your work.

________________________________

**Comment by fpaquet** [comment]
We're closing this issue due to lack of information.
Not reproducible.
