### ISSUE TITLE
Segmentation fault in gtk_sheet_position_child ()

### ISSUE THREAD

**Issue by songqingshan** [fpaquet/gtksheet#31]
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006fb5b8ed in gtk_sheet_position_child ()
   from C:\msys64\mingw64\bin\libgtksheet-4.0-1.dll

**Comment by fpaquet** [comment]
Can you produce a stack trace?

**Comment by songqingshan** [comment]
Hello,
Thanks for your response.
Attached is only a stack trace, which you already have. I cannot produce more.

________________________________

**Comment by fpaquet** [comment]
We're closing this issue due to lack of information.
Not reproducible.
