### ISSUE TITLE
GTK_SHEET_VERTICAL_JUSTIFICATION_DEFAULT, GTK_SHEET_VERTICAL_JUSTIFICATION_TOP AND GTK_SHEET_VERTICAL_JUSTIFICATION_MIDDLE are the same (no difference). 

### ISSUE THREAD

**Issue by songqingshan** [fpaquet/gtksheet#32]
GTK_SHEET_VERTICAL_JUSTIFICATION_DEFAULT, GTK_SHEET_VERTICAL_JUSTIFICATION_TOP AND GTK_SHEET_VERTICAL_JUSTIFICATION_MIDDLE are the same (no difference). 
only GTK_SHEET_VERTICAL_JUSTIFICATION_BOTTOM can show difference.

**Comment by fpaquet** [comment]
confirmed

GTK_SHEET_VERTICAL_JUSTIFICATION_DEFAULT and GTK_SHEET_VERTICAL_JUSTIFICATION_TOP is same by definition.

GTK_SHEET_VERTICAL_JUSTIFICATION_TOP and GTK_SHEET_VERTICAL_JUSTIFICATION_MIDDLE can be same, depending on number of text lines and free space

I found the following comment in the code:

	/* Vertical justification is quantisized,
	   so that all text lines using the same font appear
	   vertically aligned, even if adjacent columns have
	   different vjust settings.
	   */

After several tries, i am tempted to drop the quantization.
Have to do more testing...

**Comment by fpaquet** [comment]
After several tests, i'm dropping quantization.
It's unclear to me, what this "feature" was meant to provide.

**Comment by fpaquet** [comment]
Fixed in GtkSheet Version 4.3.8 branch gtk3_fixes
to be published soon in branch gtk3

Thank you for reporting
