### ISSUE TITLE
*** No rule to make target 'libgtksheet-4.0.la', needed by 'testgtksheet'.

### ISSUE THREAD

**Issue by Xliff** [fpaquet/gtksheet#36]
This seems like a missed Makefile rule, however I cannot find out how .la files are properly generated by libtool, only that it is libtool that supposed to generate them.

Can someone more familiar with the build system help?

**Comment by fpaquet** [comment]
What platform are you using?
Did you run configure script?
Can you post output of configure script?

**Comment by Xliff** [comment]
I am on Linux.

Here is the output from ./configure:

```
./configure
configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."/build-aux
```

**Comment by fpaquet** [comment]
Looks as if some build tools are missing on your Linux.
Try running "autoreconf -f -i" before "configure"

https://askubuntu.com/questions/27677/cannot-find-install-sh-install-sh-or-shtool-in-ac-aux

**Comment by danyeaw** [comment]
I came across this error as well, the first time I ran `autoconf -i` I didn't have the gtk3-dev dependencies installed. I needed to rerun `autoreconf -f -i` after having all the dependencies installed.

**Comment by fpaquet** [comment]
We cannot eliminate the need to run 'autoreconf -f -i' because different os have different build environments installed on their systems.

Thank you for feedback.
